name: Deploy to VPS on Merge

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Add VPS SSH fingerprint
        run: ssh-keyscan -H 103.145.50.241 >> ~/.ssh/known_hosts

      - name: Deploy code to VPS
        run: scp -r ./* omsaitiffin@103.145.50.241:/home/omsaitiffin/cp_sparkhub_in
